server:
    port: 8080
spring:
    cloud:
        stream:
            bindings:
                sourceOneChannel:
                    group: sourceOnegroup
                sourceTwoChannel:
                    group: sourceTwogroup
